algoritmo "EXERCÍCIO 03."
// DESCIPLINA : LABORATÓRIO DE ALGORITMOS
// DOCENTE    : DYEGO MAGNO OLIVEIRA SOUZA
// DISCENTE   : ROBERTO FERNANDES ROCHA
// DATA ATUAL : 2021
var
   N1 :inteiro
inicio
   escreval ("digite um número inteiro:")
   leia (N1)
   se (N1 % 4 = 0) então
      escreval (N1," é um número múltiplo de 4: ")
   senao
      escreval (N1," Náo é um número múltiplo de 4: ")
   fimse
fimalgoritmo