algoritmo "Exercício 06."
// DESCIPLINA : LABORATÓRIO DE ALGORITMOS
// DOCENTE    : DYEGO MAGNO OLIVEIRA SOUZA
// DISCENTE   : ROBERTO FERNANDES ROCHA
// DATA ATUAL : 2021
var
   D, C, consm :real
inicio
escreval ("")
escreva (" Qual distância foi percorrida? ")
leia (D)
escreva (" Qual era o volume em litros de combustível? ")
leia (C)
consm <- D / C
escreval (" O consumo médio do automóvel foi de", consm:4:1)

fimalgoritmo