algoritmo "Exercício 04"
// DESCIPLINA : LABORATÓRIO DE ALGORITMOS
// DOCENTE    : DYEGO MAGNO OLIVEIRA SOUZA
// DISCENTE   : ROBERTO FERNANDES ROCHA
// DATA ATUAL : 2021
var
    N1, soma :real
inicio
      escreval ("+-+-+-+-+-+-+-+-+-+-+-+-+-+")
      escreva  ("   Digite um numero real:   ")
      leia (N1)
      escreval ("")
      soma <- N1 * N1
      escreval ("O quadrado de", N1, " é", soma)
      escreval ("-------------------------")
fimalgoritmo